POST http://localhost:8080
Content-Type: application/json

{
  "username": "aaa",
  "value": "content"
}
###
GET http://localhost:8090/user/1

###
GET http://localhost:8090/order/shop?pageNum=1&pageSize=10&shopId=1